name: g4
channels:
  - conda-forge
  - defaults
dependencies:
  - geant4
  - root
  - cmake
  - nlohmann_json
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - jinja2
    - uproot
    - awkward
    - plotly
    - python-multipart
